version: '3'
services:
  mongo_db:
    #container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  api:
    #container_name: frontend_container
    build: .
   # ports:
     # - 4000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
      NAME: Trulymittal
    depends_on:
      - mongo_db
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - api
    ports:
      - 80:80
volumes:
  mongo_db: {}
  